### ISSUE TITLE
invalid version format

### ISSUE THREAD

**Issue by dev-ankitgupta** [dispatch/dispatch#86]
Getting this error intermittently if I try to hit 1000s of URL async.
Code calls a third party API to get XML data, parses to JSON and pushes JSON to another service.

``` log
16:43:39.703 [New I/O  worker #1] DEBUG c.n.h.c.p.n.NettyAsyncHttpProvider - Unexpected I/O exception on channel [id: 0x41089729, /10.100.3.41:61809 => stage.test.com/1.1.1.1:80]
java.lang.IllegalArgumentException: invalid version format: <HTML>
        at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:102) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:105) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:187) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:140) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:128) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:548) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:445) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:94) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:372) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:246) ~[netty-3.4.4.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38) ~[netty-3.4.4.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_09]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_09]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_09]
```

**Comment by farmdawgnation** [comment]
Hi there,

It looks like you've filed an issue on dispatch/dispatch. This is the repo for the "classic" version of dispatch. This version is no longer maintained.

If you're looking for the actively maintained version of dispatch, check out [dispatch/reboot](https://github.com/dispatch/reboot) on GitHub.

Thanks!
The Dispatch Team
